const mongoose = require('mongoose');
const { Schema } = mongoose;

const leadSchema = new Schema(
  {
    leadId: { type: String, default: () => new mongoose.Types.ObjectId().toString(), unique: true },
    createdBy: { type: String, required: true },
    updatedBy: { type: String },
    assignedBy: { type: String },
    softDeleted: { type: Boolean, default: false },
    lastCallUpdated: { type: Date, default: Date.now },
    lastCallActivity: { type: Number, default: null },
    firstName: { type: String, required: true },
    lastName: { type: String },
    salutation: { type: String },
    stage: { type: String },
    status: { type: String, required: true, default: 'CL' },
    description: { type: String },
    language: { type: Number },
    rating: { type: Number, default: 1 },
    citizen: { type: String },
    city: { type: String },
    potentialReferral: { type: Boolean },
    executive1: { type: String },
    executive2: { type: String },
    executive3: { type: String },
    mobile: { type: String, unique: true },
    mobile2: { type: String },
    mobile3: { type: String },
    phone: { type: String },
    phone2: { type: String },
    callbacks: { type: Date },
    personalEmail: { type: String, unique: true, lowercase: true },
    businessEmail: { type: String, unique: true, lowercase: true },
    discussion: { type: Array },
    sourceFile: { type: String, default: null },
    sourceType: { type: Number },
    sourceName: { type: String, required: true },
    ib1: { type: String },
    ib2: { type: String },
    ib3: { type: String },
    isFavorite: { type: Boolean, default: false },
    dbCompany: { type: String },
    gender: { type: Number },
    dob: { type: Date },
    maritalStatus: { type: Number },
    expired: { type: Boolean, default: false },
    expiredAt: { type: Date },
    expectedInvestment: { type: String },
    companyName: { type: String },
    areaOfBusiness: { type: Number },
    positionInCompany: { type: Number },
    registeredMail: { type: Number },
    registeredSms: { type: Number },
    jobTitle: { type: String },
    location: { type: Number },
    leadLocation: { type: String },
    request_url: { type: String },
    referredBy: { type: String },
    isKYCCompleted: { type: Boolean, default: false },
    platform: { type: String },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.models.lead || mongoose.model('lead', leadSchema);
